name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [8, 11, 16]
        experimental: [false]
        include:
          - java: 17-ea
            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@master
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Configure Gradle
      run: |
        mkdir -p ~/.gradle
        echo "org.gradle.jvmargs=-Xms512M -Xmx4g -XX:MaxPermSize=1024m -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options=\"-Xmx1g\"" >> ~/.gradle/gradle.properties
    - name: Build with Gradle
      env:
        TAG_NAME: ${{ steps.previoustag.outputs.tag }}
      run: ./gradlew build
    - name: Analyze
      if: ${{ github.ref == 'refs/heads/master' && matrix.java == '8' }}
      env:
        TAG_NAME: ${{ steps.previoustag.outputs.tag }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: ./gradlew codeCoverageReport coverallsJacoco
    - name: Publish
      if: ${{ github.ref == 'refs/heads/master' && matrix.java == '8' }}
      env:
        TAG_NAME: ${{ steps.previoustag.outputs.tag }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNINGKEY }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNINGPASSWORD }}
        ORG_GRADLE_PROJECT_mavenUser: ${{secrets.MAVENUSER}}
        ORG_GRADLE_PROJECT_mavenPassword: ${{ secrets.MAVENPASSWORD }}
      run: ./gradlew publish
